Initial taskq import
A namespace collision occurs between the OpenSolaris/Illumos `struct
proc` and the Linux `struct proc`, which are used for different things
on each platform. On OpenSolaris/Illumos, this type can also be
referenced through the proc_t typdef, so some adjustments have been made
to use that in place of `struct proc`. First, the forwarding definition
in taskq.h has been removed. Second, the definitions of
taskq_create_proc and taskq_create_sysdc have been changed to use proc_t
instead of struct proc. Lastly, In addition, the tq_proc field of the
taskq struct has had its type changed from struct proc to proc_t.

Also return statements used NULL in functions that return integers.
These have been changed to 0 to avoid the following GCC warning/error:

error: return makes integer from pointer without a cast [-Werror]

Another complaint of GCC is in taskq_d_thread() where we can have an
uninitialized access to the variable `w` when the TQBUCKET_CLOSE flag is
set. This is harmless because the logical expression in question is ((w
== -1) || (bucket->tqbucket_flags & TQBUCKET_CLOSE)), which means that
the result will be the same regardless, but this breaks some builds, so
we fix it by preinitializing w to 0.

taskq_id_arena has been removed with preprocessor directives in favor of
making the instance id always be 0 on Linux.

The code needed for THREADS_CPU_PCT has been disabled with #ifdef.

Some mutex initialization was added.

Signed-off-by: Richard Yao <ryao@gentoo.org>